title: Sai Sankeerth Sarvade
description: Hi There, welcome to my portfolio.
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "http://www.saisarvade.me/" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: saisarvade
image: /thumbnail-jumbo.png
twitter:
  username: saisarvade

plugins:
  - jekyll-target-blank

target-blank:
    rel: noopener

header_page_refs: ['now', 'about', 'contact']
